# ingress-nginx-instana.yaml
controller:

    extraVolumes:
      - name: instana-tracing-dependencies
        emptyDir: {}
      - name: nginx-configuration

    extraVolumeMounts:
      - name: instana-tracing-dependencies
        mountPath: /instana/nginx
    #   - name: nginx-configuration # Be sure to mount your nginx.conf file with the Instana configurations!
    #     mountPath: /etc/nginx/nginx.conf

    extraInitContainers:
      - name: instana-tracing-dependencies
        image: instana-nginx-init
        volumeMounts:
          - name: instana-tracing-dependencies
            mountPath: /instana/nginx